### Post Book
POST http://localhost:5292/api/v1/Books
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJmZW1pQG1haWwuY29tIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiIzYjA0OWI4NS1hZDRlLTQ5OGUtODM4My0wM2M5MTcwMDIxOTkiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiJ9.rVLSCb-iM1wVGAvzS3ngxv4goVVNt-OvU8UGewTqZIA

{
  "title": "Quantum Mechanics",
  "genre": "TextBooks",
  "inventory": 3
}

### Get Books
GET http://localhost:5292/api/v1/Books/categorize?genre=Novel
Content-Type: application/json

### Get Books by Genre
GET  http://localhost:5292/api/v1/Books
Content-Type: application/json

### Get Book by Id
GET  http://localhost:5292/api/v1/Books/42a5fe40-b20a-49d6-b0b4-b719db8ce9d9
Content-Type: application/json

### Search book
GET http://localhost:5292/api/v1/Books/search
Content-Type: application/json
 
### Delete Books
DELETE http://localhost:5292/api/v1/Books/70401471-8f4e-475e-bab8-b6cf8d40b12b
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJmZW1pQG1haWwuY29tIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiIyMDUzZTIwZi04YjkzLTQ0ZTMtOGUwNi1kYzhkZjRmNjUzODIiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiJ9.HdHbyTiV1ASuRXX22whbY_WXULtZYY2FnE0-A-qYM2A
