### Post Loan (user = test1)
POST http://localhost:5292/api/v1/Loans
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJlcmlrQG1haWwuY29tIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiI0MGQ0ZWI4ZC00MTAzLTQ5MTktYWRkMC05MDAyM2ZkM2FhMGQiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJDbGllbnQifQ.W4cT6brSjzWLLsHEdO6lirsYl_gTI6cxX14nzHheZVg

{
  "loanBooks": [
    {
      "bookId": "e160f9b9-9ab7-459c-93bb-3915218134f5"
    },
    {
      "bookId": "94b367b8-5bd1-4438-b79e-79d1058491fb"
    },
    {
      "bookId": "76d981a9-f048-415e-b231-64dca9084564"
    }
  ]
}

### Return Loan (enter loanId)
PUT http://localhost:5292/api/v1/Loans/return/fa0375c0-7b4e-4df3-a39c-a7574e47b194
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJlcmlrQG1haWwuY29tIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiI0MGQ0ZWI4ZC00MTAzLTQ5MTktYWRkMC05MDAyM2ZkM2FhMGQiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJDbGllbnQifQ.W4cT6brSjzWLLsHEdO6lirsYl_gTI6cxX14nzHheZVg

### Return Loan (enter loanId)
PUT http://localhost:5292/api/v1/Loans/return/94791661-1a86-4a8c-8c86-79ce1cfcc331
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJ0b21AbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImRhZTg2ODI1LTAwYjUtNGUwOC05NDkyLTU0ZTgzN2M5YWNmYyIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkNsaWVudCJ9.T-jXytCxtjCN99pE_Pox9FqOluTf_zeQQx_MPAFgiaA


### Get Loans by UserId (enter userId)
GET http://localhost:5292/api/v1/Loans/user/40d4eb8d-4103-4919-add0-90023fd3aa0d
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJlcmlrQG1haWwuY29tIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiI0MGQ0ZWI4ZC00MTAzLTQ5MTktYWRkMC05MDAyM2ZkM2FhMGQiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJDbGllbnQifQ.W4cT6brSjzWLLsHEdO6lirsYl_gTI6cxX14nzHheZVg

### Get all Loans admin
GET http://localhost:5292/api/v1/Loans
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJmZW1pQG1haWwuY29tIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiJkNjA0NGZjZi04M2U0LTQ0Y2EtYmEyNS0zMGI3NDUyYmJmZTAiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiJ9.Ii0V11o8y_noAIFe5oPs0sfKi2dheVMJ7YTDDrPm7y0
