### Post Loan (user = test1)
POST http://localhost:5292/api/v1/Loans
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJqaW1AbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImNiOTcwOTk1LWMwOGYtNDViZC04NTQ4LTRiOWNhMjQyMTBhNSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkNsaWVudCJ9.IlV__0oUpcvPfF2fHgUciY1xbgfRN9smDu2pXE89LSE

{
  "loanBooks": [
    {
      "bookId": "99d77689-e022-4463-9ca4-0cdcd97fd8a8"
    },
    {
      "bookId": "dce0723c-0e19-4473-be49-40fdbe5c26fb"
    }
  ]
}

### Return Loan (enter loanId)
PUT http://localhost:5292/api/v1/Loans/return/fa0375c0-7b4e-4df3-a39c-a7574e47b194
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJlcmlrQG1haWwuY29tIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiI0MGQ0ZWI4ZC00MTAzLTQ5MTktYWRkMC05MDAyM2ZkM2FhMGQiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJDbGllbnQifQ.W4cT6brSjzWLLsHEdO6lirsYl_gTI6cxX14nzHheZVg

### Return Loan (enter loanId)
PUT http://localhost:5292/api/v1/Loans/return/94791661-1a86-4a8c-8c86-79ce1cfcc331
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJ0b21AbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImRhZTg2ODI1LTAwYjUtNGUwOC05NDkyLTU0ZTgzN2M5YWNmYyIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkNsaWVudCJ9.T-jXytCxtjCN99pE_Pox9FqOluTf_zeQQx_MPAFgiaA


### Get Loans by UserId (enter userId)
GET http://localhost:5292/api/v1/books/cb970995-c08f-45bd-8548-4b9ca24210a5
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJqaW1AbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImNiOTcwOTk1LWMwOGYtNDViZC04NTQ4LTRiOWNhMjQyMTBhNSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkNsaWVudCJ9.IlV__0oUpcvPfF2fHgUciY1xbgfRN9smDu2pXE89LSE

### Get all Loans admin
GET http://localhost:5292/api/v1/Loans
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJmZW1pQG1haWwuY29tIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiI3Y2I2MWMzYi1mZGU1LTQ2N2QtYjVmOC1mZDhjZGE5N2MyMjEiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiJ9.8bUOVC2ICtHP78C8QTsNXl_y5aWsCNpAy1gvY_BJR8M
